services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=UTC

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 turnosBanco.asgi:application
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

