# Generated by Django 3.0 on 2024-06-07 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Cedula must be 1 to 10 digits long', regex='^\\d{1,10}$')])),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
