# Generated by Django 3.0 on 2024-06-05 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtenCliente',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='Gerencia',
        ),
        migrations.DeleteModel(
            name='Turnos',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cedula',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Cedula must be 1 to 10 digits long', regex='^\\d{1,10}$')]),
        ),
    ]
