# Generated by Django 3.0 on 2024-06-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_usuarios', '0002_turnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnosPasados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('turno', models.CharField(max_length=5)),
                ('caja', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
